### ISSUE TITLE
Does not compile on linux with musl libc

### ISSUE THREAD

**Issue by doughdemon** [Leont/crypt-rijndael#11]
Fails with "unkown type name '__uint32_t'". The problem is that musl libc's <sys/types.h> defines _SYS_TYPES_H but not __uint32_t (though it does uint32_t and u_int32_t). musl cannot reliably be detected using macros.

Why can't <stdint.h> types be used by default or just 'unsigned int' for UINT32 and 'unsigned char' for UINT8?

**Comment by doughdemon** [comment]
See http://bluedragon-tinderbox.freeharbor.net/dev-perl/Crypt-Rijndael-1.110.0-r1/temp/build.log for a log of a failed build.

**Comment by Leont** [comment]
> Fails with "unkown type name '__uint32_t'". The problem is that musl libc's defines _SYS_TYPES_H but not __uint32_t (though it does uint32_t and u_int32_t). musl cannot reliably be detected using macros.

Actually, perl already defines an U32 and U8, it's probably easiest to reuse those.

> Why can't types be used by default or just 'unsigned int' for UINT32 and 'unsigned char' for UINT8?

That is suboptimally portable, specially 'unsigned int'.

**Comment by doughdemon** [comment]
> > Why can't types be used by default or just 'unsigned int' for UINT32 and 'unsigned char' for UINT8?
> 
> That is suboptimally portable, specially 'unsigned int'.

Right, int is only at least 32 bits.

**Comment by Leont** [comment]
> Right, int is only at least 32 bits.

Actually, it's only at least 16 bytes, though I don't think perl runs on any such platform.

**Comment by doughdemon** [comment]
Leon Timmermans wrote:
> > Right, int is only at least 32 bits.
> 
> Actually, it's only at least 16 bytes, though I don't think perl runs on any such platform.

I forgot to add "on posix systems".

**Comment by kentfredric** [comment]
I suspect the fix won't be different for `armv7a`, however, just got a second report here with `$VERSION=1.13` ( also on gentoo as the original report was )

https://bugs.gentoo.org/612096
