### ISSUE TITLE
Make a new release (1.14)

### ISSUE THREAD

**Issue by dehy** [Leont/crypt-rijndael#15]
I'm currently using Data-Entropy perl module that reference Crypt::Rijndael and would like to deploy it on alpine linux but the last available version is 1.13 that do not contain the musl fix. Do you plan to make a new release?

Thanks !

**Comment by marlencrabapple** [comment]
Seconded. Dealing with the exact same thing.

**Comment by Leont** [comment]
I'll try to look at it this week!

**Comment by wchristian** [comment]
@Leont 	ping. still an issue

**Comment by Leont** [comment]
Sorry about the delay, I just released it.

**Comment by wchristian** [comment]
Cheers. :D
