### ISSUE TITLE
Buffer overwrite in XS code

### ISSUE THREAD

**Issue by todd-richmond** [Leont/crypt-rijndael#19]
It looks to me that release 1.15 introduced a buffer overwrite in an unnecessary attempt to end with a \0. the problem is that encrypt() call newSV(size) but then writes buffer[size] which is 1 greater

the \0 is not needed (and wasn't in 1.12) because perl handles lengths and trailing \0. This isn't a string data so \0 doesn't apply

**Comment by Leont** [comment]
`newSV` is documented as:

> Creates a new SV. A non-zero len parameter indicates the number of bytes of preallocated string space the SV should have. An extra byte for a trailing NUL is also reserved.

So I think it's correct. Or did valgrind/asan/etc say otherwise?

**Comment by todd-richmond** [comment]
ah - you are correct. I didn't see that line in the doc. We are seeing a crash in multithreaded encodes but it must be something else
